version: '3'
services:
  rocketchat:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
      - '27017:27017'
    # links:
    #   - mongo
    environment:
      ROOT_URL: 'http://localhost:3000'
      MONGO_URL: 'mongodb://127.0.0.1:27017/meteor'
      PORT: 3000
    volumes:
      - '$PWD:/app'
      - '$HOME/.meteor/packages:$HOME/.meteor/packages'
      - '$HOME/.meteor/package-metadata:$HOME/.meteor/package-metadata'
